### ISSUE TITLE
client.rb raises an exception on slow builds

### ISSUE THREAD

**Issue by bonniee** [oreillymedia/atlas-api#1]
In client.rb, if the build takes longer than 100 seconds, an exception is raised. https://github.com/oreillymedia/atlas-api/blob/master/lib/atlas-api/client.rb#L26

For my current manuscript (_Learning React Native_), builds routinely take longer than 100 seconds.

Can you please explain the benefit of raising an exception here? The user can CTRL+C at any time, so I don't see the reason behind having a hardcoded timeout.

**Comment by nadamsoreilly** [comment]
Apologies for the long delay. This problem was addressed in PR: https://github.com/oreillymedia/atlas-api/pull/4
